config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
resources :users, except: [:new]
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get 'logout', to: 'sessions#destroy'
resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
has_many :article_categories
has_many :categories, through: :article_categories

validates :title, presence: true, length: {minimum: 6, maximum: 100}
validates :description, presence: true, length: {minimum:2, maximum: 5000}
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
belongs_to :article
belongs_to :category
end 

app/models/category.rb
class Category < ApplicationRecord
validates :name, presence: true, length: {minimum: 3, maximum: 25}
validates_uniqueness_of :name
has_many :article_categories
has_many :articles, through: :article_categories
end 

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
validates :username, presence: true, 
                     uniqueness: {case_sensitive: false }, 
                     length:{minimum: 3, maximum: 25}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
                     validates :email, presence: true, 
                     uniqueness: {case_sensitive: false }, 
                     length:{ maximum: 105},
                     format: {with: VALID_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user

        @current_user ||= User.find(session[:user_id])  if session[:user_id]

    end 

     def logged_in?
        !!current_user
        end 

def require_user
if !logged_in?
    flash[:alert] = "You must be logged in!"
    redirect_to login_path
end
end 

    end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
before_action :require_user, except: [:show, :index]
before_action :require_same_user, only: [:edit, :update, :destroy]



    def show 
    end 

def index
@articles = Article.all
 end 


 

 def new
@article = Article.new
 end

 def edit

 end 

 def create
@article = Article.new(article_params)
@article.user = current_user
if  @article.save
    flash[:notice] = "Article was created successfully."
redirect_to  @article
else 
render 'new'
end 
end 


def update
if @article.update(article_params)
flash[:notice] = "Article was updated successfully"
redirect_to @article

else 
render 'edit'
end 
end 

def destroy
@article.destroy
redirect_to articles_path
end 


private 

def set_article
@article = Article.find(params[:id])
end 


def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
end 

def require_same_user
if current_user != @article.user && !current_user.admin?
    flash[:alert] = "You are not allowed to edit this article"
    redirect_to @article
end
end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :require_admin, except: [:index, :show]


def new 
@category = Category.new
end 

def create
@category = Category.new(category_params)
if @category.save
flash[:notice] = " Category succesfully created"
redirect_to @category
else
render 'new'
end 
end 

def edit
@category = Category.find(params[:id])
end 


def update 
@category = Category.find(params[:id])
if @category.update(category_params)
  flash[:notice] = "Category name updated successfully"
  redirect_to @category

else
render 'edit'
end 
end 

def index
@categories = Category.all
end 

def show
@category  = Category.find(params[:id])
@articles = @category.articles
end 

private

def category_params
    params.require(:category).permit(:name)

end 

def require_admin
  if !(logged_in? && current_user.admin?)
  flash[:alert] = "Only admins can add a category"
    redirect_to categories_path
  end
end 


end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end 

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end 

def create 
user = User.find_by(email: params[:session][:email].downcase)
if user && user.authenticate(params[:session][:password])
session[:user_id] = user.id 
flash[:notice] = "Logged in successfully"
redirect_to user


else 
    flash.now[:alert] = "Wrong password or email"
    render 'new'
end 

end 




def destroy
session[:user_id] = nil
flash[:notice] = "Logged out"
redirect_to root_path
end 



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :require_user, only: [:edit, :update]
before_action :require_same_user, only: [:edit, :update, :destroy]




def show 

@articles = @user.articles
end 

def index
@users = User.all
end

def new
    @user = User.new
end 

def edit 

end 

def update
    @user = User.find(params[:id])
if @user.update(user_params)
flash[:notice] = "Succesfully updated"
redirect_to @user
else
    render 'edit'
end
end 



def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
flash[:notice] = "Welcome #{@user.username}"
        redirect_to articles_path
    else
render 'new'
    end
end 


def destroy
@user.destroy
session[:user_id] = nil if @user == current_user
flash[:notice] = "Account successfully deleted"
redirect_to articles_path
end 

private
def user_params
params.require(:user).permit(:username, :email, :password)
end

def set_user
    @user = User.find(params[:id])

end

def require_same_user 
if current_user !=@user && !current_user.admin?
    flash[:alert] = "You are not allowed to edit this user"

redirect_to @user
end

end





end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
email_address = user.email.downcase
hash = Digest::MD5.hexdigest(email_address)
size = options[:size]
gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block mt-3")
    end 


    

    


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
    <div class="row justify-content-md-center"> 
    <div class="col-12 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  <div class="card-header font-italic">
  <% if article.user %>
    By  <%= link_to article.user.username, user_path(article.user) %>
<% end %>
   
<% if article.categories.any? %>

<div class= "mt-2"><%= render article.categories %></div>
<% end %>



  </div>
  <div class="card-body">
    <h5 class="card-title">  <%= link_to article.title, article_path(article), class: "text-primary" %> </h5>
    <p class="card-text"><%=  truncate(article.description, length:100) %></p>

  
  </div>
  <div class="card-footer text-muted">
    <small> Created   <%= time_ago_in_words(article.created_at) %> ago,

    edited  <%= time_ago_in_words(article.updated_at) %> ago </small>
  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container bg-dark">
<div class= "row justify-content-center">

<div class = "col-10">
<%= render 'shared/errors', obj: @article %>



<%= form_with(model: @article, class: "shadow p-3 mb-3 bg-dark rounded  row justify-content-center", local: true) do |f| %>
<div class = "form-group row">
 <%= f.label  :title, class: "col-1 col-form-label text-light" %> 
<div class= "col-10">

<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>

 </div>
</div>



<div class = "form-group row mt-3">
<%= f.label  :description, class: "col-1 col-form-label text-light" %> 
<div class= "col-10">
<%= f.text_area :description, rows: 10, class: "form-control shadow rounded" , placeholder: "Write your Article here.." %>
</div>
</div>

<div class = "form-group row mt-3">
<%= f.label  :category, class: "col-1 col-form-label text-light" %> 
<div class= "col-10">
<%= f.collection_select(:category_ids, Category.all, :id, :name,

{prompt: "Make your selection from the list below(can be empty)"}, {multiple: true, size: 2, class: "custom-select shadow rounded"}) %>

</div>
</div>






<div   class="form-group row justify-content-center mt-2">
 <%= f.submit   class: "btn btn-primary   col-2 col-form-label " %> 
 </div>
    <% end %>
</div>

<div   class= "mb-3" 

<%=  link_to 'Return to articles', articles_path(@article), class: 'btn btn-primary  col-3 mb-3'  %>
</div>
</div>
</div>


    

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">   Edit  Article </h1>

    
    <%= render 'form' %>
    

app/views/articles/index.html.erb
<h1 class="text-center mt-4"> Articles </h1>
<%= render 'article' %>






    

app/views/articles/new.html.erb
<h1 class="text-center mt-4">   Create an Article </h1>



<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4 "> <%= @article.title %> </h2>

<div class="container mt-4  min-vh-100">
    <div class="row justify-content-md-center"> 
    <div class="col-12 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  <div class="card-header font-italic">
  By  <%= @article.user.username if @article.user %>
<% if @article.categories.any? %>
<% render @article.categories %> 
<% end %>

  </div>

  <div class="card-body mt-3">
    <div class="card-text text-left mt-3"><%= simple_format ( @article.description) %></div>

</div>

  <div class="card-footer text-muted mb-5">

  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
<%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary" %>
<%= button_to "Delete", article_path(@article), class: "btn btn-primary col-md-1 mt-3", method: :delete %>

<% end %>

    <small> Created   <%= time_ago_in_words(@article.created_at) %> ago,

    edited  <%= time_ago_in_words(@article.updated_at) %> ago </small>
  </div>
</div>
</div>
</div>
</div>

app/views/categories/_category.html.erb
<%= category.name %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:  @category %>

<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-dark rounded  row justify-content-center ", local: true) do |f| %>
<div class = "form-group row">


 <%= f.label  :name,"Category name", class: "col-1 col-form-label text-light" %> 
<div class= "col-10">

<%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>

 </div>
</div>


<div   class="form-group row justify-content-center mt-2  ">
 <%= f.submit class: "btn btn-primary   col-2 col-form-label" %> 
 </div>
    <% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 ">   Edit  category</h1>

<div class="container bg-dark min-vh-100 mb-5">
<div class= "row justify-content-center min-vh-100 mb-5">

<div class = "col-10 mt-5  ">

<%= render 'form' %>
</div>

<div   class= "mb-3" 

<%=  link_to 'Return to articles', articles_path, class: 'btn btn-primary  col-3 mb-3'  %>
</div>
</div>
</div>


    

app/views/categories/index.html.erb
<div  class= "min-vh-100">

<h1 class="text-center mt-4"> Categories </h1>

<div class="container">
<% @categories.each do |category| %>
    <div class="row justify-content-md-center"> 
    <div class="col-12 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  

  <div class="card-body">
    <h5 class="card-title">  <%= link_to category.name, category_path(category), class: "text-primary" %> </h5>
    <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
    <% if current_user.admin? %>


<% end %>

    </div>
  <div class="card-footer text-muted">
    <small> Created   <%= time_ago_in_words(category.created_at) %> ago,

    edited  <%= time_ago_in_words(category.updated_at) %> ago </small>
  </div>
</div>
</div>
</div>
<% end %>
</div>



</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 ">   Create a New category</h1>

<div class="container bg-dark min-vh-100 mb-5">
<div class= "row justify-content-center min-vh-100 mb-5">

<div class = "col-10 mt-5  ">

<%= render 'shared/errors', obj:  @category %>

<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-dark rounded  row justify-content-center ", local: true) do |f| %>
<div class = "form-group row">


 <%= f.label  :name,"Category name", class: "col-1 col-form-label text-light" %> 
<div class= "col-10">

<%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>

 </div>
</div>


<div   class="form-group row justify-content-center mt-2  ">
 <%= f.submit class: "btn btn-primary   col-2 col-form-label" %> 
 </div>
    <% end %>
</div>

<div   class= "mb-3" 

<%=  link_to 'Return to articles', articles_path, class: 'btn btn-primary  col-3 mb-3'  %>
</div>
</div>
</div>


    

app/views/categories/show.html.erb
<div  class= "min-vh-100">



<h1 class= "text-center  min-vh-100, mb-3">Category:  <%= @category.name %> </h1>



<div class= "text-center mt-3">Articles </div>

</h2>


<p class = " text-center, mb-1, col-12">


<%= render 'articles/article' %>

</p>

</div>

</div>

app/views/layouts/_footer.html.erb
<div class = "col-12   d-flex flex-column">
<footer id="sticky-footer"  class=" py-3 bg-dark   text-white-50 mt-5   ">
<div class="container text-center">
<small>Copyright &copy Benshalom 2022.</small>
</div>
</footer>

</div>

app/views/layouts/_messages.html.erb
<div class= "container">

<% flash.each do |name, msg| %>
    

  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

</button>

    </div>
    
      <% end %>
      </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

<%= link_to "JLIC", root_path, class: "navbar-brand", id: "logo"  %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

        <%= link_to "View Articles", articles_path, class: "nav-link" %>


        </li>
        <li class="nav-item">
        
        <% if logged_in? %>
          <%= link_to "Create new Article", new_article_path, class: "nav-link" %>

<% end %>

        </li>

        <%= link_to "Bloggers", users_path, class: "nav-link" %>
        

      <% if logged_in? %>
        <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        <%= link_to " Categories", categories_path, class: "nav-link" %>



        <% if logged_in?  && current_user.admin? %>
        <%= link_to " Create Categories", new_category_path, class: "nav-link" %>
<% end %>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

        <ul class="navbar-nav me-2 mb-2 mb-lg-0">
                <li class="nav-item ">
              <%= link_to current_user.username, user_path(current_user), class: "nav-link  " %>

                </li>
                <li class="nav-item">
                </li>
            </ul>
</div>



<% else %>
<%= link_to "Login", login_path, class: "nav-link" %>

<%= link_to "SignUp", signup_path, class: "nav-link" %>


<% end %>


      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redeemed Gospel Church, Zimmerman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render 'layouts/navigation' %>

  <%= render 'layouts/messages' %>

  
  <%= yield %>
<div class= "container-text-center  mt-5"> 
  <%= render 'layouts/footer' %>
  </div>
  </body>

  
</html>

app/views/pages/about.html.erb
<h1>  Welcome to the About page </h1>


<%=  link_to 'Articles Listing ', articles_path(@article) %> |
<%=  link_to 'Home Page ', root_path(@article) %> 

app/views/pages/home.html.erb
<div class="container mt-5" >

<div class="jumbotron text-center  d-flex flex-column min-vh-100 ">
  <h1 class="display-4 ">Redeemed Gospel Church, Zimmerman</h1>
  <p class="lead">Jesus Life Impacting Centre.</p>
  <hr class="my-4">
  <p>Bloggers' Corner</p>
  <p class="lead">
  

    <%= link_to "Sign up", signup_path, class: "btn btn-primary" %>
  </p>
  
</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>


<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
<ul> 
<% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
<% end %>
</ul>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

</button>
</div>


<% end %>

app/views/users/_form.html.erb
<div class="container bg-dark">
<div class= "row justify-content-center">

<div class = "col-10 mt-5">
<%= render 'shared/errors', obj: @user %>



<%= form_with(model: @user, class: "shadow p-3 mb-3 bg-dark rounded  row justify-content-center", local: true) do |f| %>
<div class = "form-group row">


 <%= f.label  :username, class: "col-1 col-form-label text-light" %> 
<div class= "col-10">

<%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>

 </div>
</div>


<div class = "form-group row mt-3 mb-5">
<%= f.label  :email, class: "col-1 col-form-label text-light" %> 
<div class= "col-10 mb-5">
<%= f.email_field :email, class: "form-control shadow rounded" , placeholder: "Enter your email address." %>
</div>
</div>

<div class = "form-group row mt-3 mb-5">
<%= f.label  :password, class: "col-1 col-form-label text-light" %> 
<div class= "col-10 mb-3">
<%= f.password_field :password, class: "form-control shadow rounded" , placeholder: "Enter your password." %>
</div>
</div>

<div   class="form-group row justify-content-center mt-2">
 <%= f.submit(@user.new_record? ?   "Sign Up" : "Update Account", class: "btn btn-primary   col-2 col-form-label") %> 
 </div>
    <% end %>
</div>

<div   class= "mb-3" 

<%=  link_to 'Return to articles', articles_path(@article), class: 'btn btn-primary  col-3 mb-3'  %>
</div>
</div>
</div>


    

app/views/users/edit.html.erb
<h1 class="text-center mt-4">   Edit your profile </h1>



<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center  text-right, d-flex flex-column ">  Bloggers </h1>

<div class="container min-vh-100">


<% @users.each do |user| %>
    
    <div class="row justify-content-md-center "> 
    <div class="col-12 mt-4">
<div class="card text-center shadow  mb-3 bg-white rounded ">
  <div class="card-header font-italic">
     <%= link_to user.username,  user %>
  </div>
  <div class="card-body">
    <h5 class="card-title">  <%= link_to gravatar_for(user, size: 90), user %> </h5>
    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>



   <%= link_to "View Profile",  user, class: "btn btn-primary"  %>

   <% if logged_in? %> 
   
   <% if  user == current_user  && !current_user.admin? %> 
<%= link_to "Edit Profile",  edit_user_path(user), class: "btn btn-primary"  %>
<%= button_to "Delete Profile", user_path(user), class: "btn btn-primary col-md-1 mt-3", method: :delete  %>

<% end %>

<% if current_user.admin? %>
<%= button_to "Delete User", user_path(user), class: "btn btn-primary col-md-1 mt-3", method: :delete  %>

<% end %>
<% end %>



  </div>
  <div class="card-footer text-muted">
    <small> Joined   <%= time_ago_in_words(user.created_at) %> ago,

  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">   Sign up </h1>



<%= render 'form' %>

app/views/users/show.html.erb
<div  class= "min-vh-100">


<h1 class= "text-center  min-vh-100, mb-3"> <%= @user.username %>'s profile 


</h1>

<h2 class="text-right, d-flex flex-column min-vh-100, mb-3"> 

<%= gravatar_for @user, size: 100  %>

<div class= "text-center mt-3">Articles by <%= @user.username%> </div>

</h2>


<p class = " text-center, mb-1, col-12">


<%= render 'articles/article', class: "" %>

</p>

</div>